How To Updates / Model Used Switched / Removed "docker-compose" (RIP)
mudler/LocalAI pull request #1417
Opened 2023-12-10 15:31 UTC by lunamidori5

**Description**
- Removed ``docker-compose`` for windows, as it now follows the ``docker compose`` like linux
- Updated the how to set up a model to use ``dolphin-2.2.1-mistral-7B`` not ``luna-ai``
- Updated the how to set up a model to use a chat template model
- Updated Getting Started page to remove docker-compose windows warning
- Updated the ``index`` file for how to folder to add SD requests

This PR fixes #1416 (at least for Mac Users that must use q4_0 models)

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-12-10 15:53 UTC, lunamidori5 commented
Also updated the pages with Tabs to make it easier to setup the file system

2023-12-11 11:59 UTC, M0Rf30 commented on docs/content/howtos/easy-setup-docker-cpu.md
> +Lets Setup our folders for ``LocalAI``
should be lowercase S for Setup

2023-12-11 12:01 UTC, lunamidori5 commented on docs/content/howtos/easy-setup-docker-cpu.md
> +We are going to run `LocalAI` with `Docker compose` for this set up.
Alright thank you! (let me see how to fix that)

2023-12-11 12:05 UTC, M0Rf30 approved these changes

2023-12-11 12:06 UTC, M0Rf30 requested changes

2023-12-11 12:06 UTC, M0Rf30 commented on docs/content/howtos/easy-setup-docker-gpu.md
> +We are going to run `LocalAI` with `socker compose` for this set up.
replace socker

2023-12-11 14:27 UTC, merged